### ISSUE TITLE
[Epic] Solver Auction CIP

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/dune-sync#27]
Solvers are changing their reward structure (yet again) and we will need to adapt what information is synced.

- [x] Create necessary tables in Orderbook Database (https://github.com/cowprotocol/services/pull/1166)
- [ ] Query for info to be streamed into Dune Community Sources (https://github.com/cowprotocol/dune-sync/pull/26)
- [ ] Construct appropriate Dune Schema for Batch Rewards.

**Comment by bh2smith** [comment]
Since I don't think its very appropriate to create even a draft PR in an external repo before we are prepared to utilize it, I will prepare the "spell" code here for later use.


```sql
{{ config(alias='batch_rewards',
        post_hook='{{ expose_spells_hide_trino(\'["ethereum"]\',
                                    "project",
                                    "cow_protocol",
                                    \'["bh2smith"]\') }}'
)}}

-- PoC Query here - <PROVIDE QUERY URL>
select
    distinct tx_hash,
    block_number,
    solver,
    data.reward_eth as unbound_reward,
    data.execution_cost,
    data.participants
from {{ source('cowswap', 'raw_batch_rewards') }}
```



From this we would write a parameterized query to dynamically impose reward capping as follows  

```sql
select 
    tx_hash, 
    solver, 
    min(max(-{{EPSILON}}, unbound_reward), {{EPSILON}} + execution_cost) 
from batch_rewards
```

For participation distribution we would build another query that "unnests" or "explodes" the participants array and transposes.

```sql
with expanded_participation as (
    select 
        block_number,
        tx_hash,
        explode(participants) as participant
    from batch_rewards
)

select 
    participant, 
    count(*) as num_solutions 
from expanded_participation
```
